# Generated by Django 4.0 on 2022-01-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_reported_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reported',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_items/'),
        ),
    ]
