# Generated by Django 4.0 on 2022-01-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_reported_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reported',
            name='srn',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
